### ISSUE TITLE
chia_bls

### ISSUE THREAD

**Issue by pinpins** [GeckoProjectMN/GeckoProject#1]
chia_bls dependency has reference to non existing URL

**Comment by GeckoProjectMN** [comment]
> chia_bls dependency has reference to non existing URL

You need to build the dependencies in the depends folder with the make command (if for Linux), then go back to the root folder and build the project with the commands:
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu
make
